export const START_GET_CHARACTERS = "START_GET_CHARACTERS";
export const SUCCESS_GET_CHARACTERS = "SUCCESS_GET_CHARACTERS";
export const ERROR_GET_CHARACTERS = "ERROR_GET_CHARACTERS";

export const START_GET_QUOTE = "START_GET_QUOTE";
export const SUCCESS_GET_QUOTE = "SUCCESS_GET_QUOTE";
export const ERROR_GET_QUOTE = "ERROR_GET_QUOTE";
export const REMOVE_QUOTE = "REMOVE_QUOTE";
